# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencias',
            options={'verbose_name_plural': 'Asistencias'},
        ),
    ]
