# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160625_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencias',
            name='nombre_match',
            field=models.CharField(default='A', max_length=100),
        ),
    ]
