# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_asistencias_nombre_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='nombre_match',
            field=models.CharField(max_length=100),
        ),
    ]
