# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_asistencias_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencias',
            old_name='update',
            new_name='update_date',
        ),
    ]
