# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160712_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencias',
            name='observacion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
