INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('AVANZAR SAN LUIS','POGGI, CLAUDIO JAVIER',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('BG JUAN B. BUSTOS','BERNABEY, RAMON ERNESTO',4,2,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('CHUBUT SOMOS TODOS','TABOADA, JORGE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('COALICION CIVICA','CARRIO, ELISA MARIA AVELINA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('COALICION CIVICA','MARTINEZ VILLADA, LEONOR MARIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('COALICION CIVICA','SANCHEZ, FERNANDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('COALICION CIVICA','TERADA, ALICIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('COMPROMISO CON SAN JUAN','CASTRO MOLINA, ENRIQUE ROBERTO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('COMPROMISO FEDERAL','ARENAS, BERTA HORTENSIA',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('COMPROMISO FEDERAL','BIANCHI, IVANA MARIA',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('COMPROMISO FEDERAL','LUSQUIÑOS, LUIS BERNARDO',4,'','',1);
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('CONCERTACION FORJA','PEREYRA, JUAN MANUEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('CULTURA, EDUCACION Y TRABAJO','PLAINI, FRANCISCO OMAR',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('DEL BICENTENARIO','CASAÑAS, JUAN FRANCISCO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('DEL BICENTENARIO','VILLAVICENCIO, MARIA TERESITA',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('DIALOGO Y TRABAJO','RAFFO, JULIO CESAR',4,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','ALEGRE, GILBERTO OSCAR',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','ALONSO, HORACIO FERNANDO',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','BEVILACQUA, GUSTAVO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','CAMAÑO, GRACIELA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','DAER, HECTOR RICARDO',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','DE MENDIGUREN, JOSE IGNACIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','EHCOSOR, MARIA AZUCENA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','GRANDINETTI, ALEJANDRO ARIEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','LAVAGNA, MARCO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','LITZA, MONICA EDITH',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','MASSA, SERGIO TOMAS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','MASSETANI, VANESA LAURA',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','MORALES, MARIANA ELIZABET',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','MOREAU, CECILIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','MOYANO, JUAN FACUNDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','PASSO, MARCELA FABIANA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','PEREZ, RAUL JOAQUIN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','PITIOT, CARLA BETINA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','SCHWINDT, MARIA LILIANA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','SELVA, CARLOS AMERICO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','SNOPEK, ALEJANDRO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','SOLA, FELIPE CARLOS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FEDERAL UNIDOS POR UNA NUEVA ARGENTINA','TUNDIS, MIRTA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE CIVICO POR SANTIAGO','ABDALA DE MATARAZZO, NORMA AMANDA',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE CIVICO POR SANTIAGO','HERRERA, JOSE ALBERTO',4,'',2,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE CIVICO POR SANTIAGO','JUAREZ, MANUEL HUMBERTO',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE CIVICO POR SANTIAGO','NAVARRO, GRACIELA',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE CIVICO POR SANTIAGO','OLIVA, CRISTIAN RODOLFO',3,'',3,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE CIVICO POR SANTIAGO','PASTORIZA, MIRTA AMELIANA',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE DE LA CONCORDIA MISIONERO','CLOSS, MAURICE FABIAN',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE DE LA CONCORDIA MISIONERO','FRANCO, JORGE DANIEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE DE LA CONCORDIA MISIONERO','RISKO, SILVIA LUCRECIA',4,'',2,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','ABRAHAM, ALEJANDRO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','ALVAREZ RODRIGUEZ, MARIA CRISTINA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','ARRIETA, GUSTAVO HECTOR',3,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','BARDEGGIA, LUIS MARIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','BARRETO, JORGE RUBEN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','BASTERRA, LUIS EUGENIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','BRITEZ, MARIA CRISTINA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CABANDIE, JUAN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CARLOTTO, REMO GERARDO',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CARMONA, GUILLERMO RAMON',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CAROL, ANALUZ AILEN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CARRIZO, NILDA MABEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CASTAGNETO, CARLOS DANIEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CASTRO, SANDRA DANIELA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CIAMPINI, JOSE ALBERTO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CIGOGNA, LUIS FRANCISCO JORGE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CLERI, MARCOS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','CONTI, DIANA BEATRIZ',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','DE PEDRO, EDUARDO ENRIQUE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','DE PONTI, LUCILA MARIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','DE VIDO, JULIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','DEPETRI, EDGARDO FERNANDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','DI STEFANO, DANIEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','DI TULLIO, JULIANA',4,2,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','DIAZ ROIG, JUAN CARLOS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','DOÑATE, CLAUDIO MARTIN',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','ESTEVEZ, GABRIELA BEATRIZ',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','FERREYRA, ARACELI SUSANA DEL ROSARIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','FRANA, SILVINA PATRICIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','FURLAN, FRANCISCO ABEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GAILLARD, ANA CAROLINA',5,'','',1);
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GALLARDO, MIRIAM GRACIELA DEL VALLE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GARCIA, MARIA TERESA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GARRE, NILDA CELIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GERVASONI, LAUTARO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GIOJA, JOSE LUIS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GOMEZ BULL, MAURICIO RICARDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GONZALEZ, JOSEFINA VICTORIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GRANA, ADRIAN EDUARDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GRANADOS, DULCE',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GROSSO, LEONARDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GUERIN, MARIA ISABEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','GUZMAN, ANDRES ERNESTO',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','HORNE, SILVIA RENEE',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','HUSS, JUAN MANUEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','IGON, SANTIAGO NICOLAS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','KICILLOF, AXEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','KIRCHNER, MAXIMO CARLOS',3,3,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','KUNKEL, CARLOS MIGUEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','LARROQUE, ANDRES',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','LLANOS, ANA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','LOTTO, INES BEATRIZ',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','MARTINEZ, NORMAN DARIO',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','MASIN, MARIA LUCILA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','MAZURE, LILIANA AMALIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','MENDOZA, MAYRA SOLEDAD',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','MENDOZA, SANDRA MARCELA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','MERCADO, VERONICA ELIZABETH',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','MORENO, CARLOS JULIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','PEDRINI, JUAN MANUEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','PEREZ, MARTIN ALEJANDRO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','RACH QUIROGA, ANALIA ALEXANDRA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','RAMOS, ALEJANDRO ARIEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','RAVERTA, MARIA FERNANDA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','RECALDE, HECTOR PEDRO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','RODRIGUEZ, MATIAS DAVID',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','RODRIGUEZ, RODRIGO MARTIN',4,2,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','RUIZ ARAGON, JOSE ARNALDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','SANTILLAN, WALTER MARCELO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','SEMINARA, EDUARDO JORGE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','SOLANAS, JULIO RODOLFO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','SORAIRE, MIRTA ALICIA',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','SORIA, MARIA EMILIA',4,2,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','TAILHADE, LUIS RODOLFO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','TOMAS, HECTOR DANIEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FRENTE PARA LA VICTORIA - PJ','VOLNOVICH, LUANA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FTE. CIVICO Y SOCIAL DE CATAMARCA','BRIZUELA DEL MORAL, EDUARDO SEGUNDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FTE. CIVICO Y SOCIAL DE CATAMARCA','JUAREZ, MYRIAN DEL VALLE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FTE. CIVICO Y SOCIAL DE CATAMARCA','QUINTAR, AMADO',4,'',2,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FTE. DE IZQUIERDA Y DE LOS TRABAJADORES','LOPEZ, PABLO SEBASTIAN',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FTE. DE IZQUIERDA Y DE LOS TRABAJADORES','PITROLA, NESTOR ANTONIO',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('FTE. DE IZQUIERDA Y DE LOS TRABAJADORES','SOSA CAPURRO, VICTORIA SOLEDAD',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('GEN','STOLBIZER, MARGARITA ROSA',4,1,1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUNTOS POR ARGENTINA','CAVIGLIA, FRANCO AGUSTIN',4,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUNTOS POR ARGENTINA','FABIANI, EDUARDO ALBERTO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUNTOS POR ARGENTINA','GIUSTOZZI, RUBEN DARIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUNTOS POR ARGENTINA','GUZMAN, SANDRO ADRIAN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','BOSSIO, DIEGO LUIS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','DAVID, NESTOR JAVIER',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','FERNANDEZ MENDIA, GUSTAVO RODOLFO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','HERRERA, LUIS BEDER',2,'',4,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','ISA, EVITA NELIDA',3,'',3,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','KOSINER, PABLO FRANCISCO JUAN',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','MACIAS, OSCAR ALBERTO',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','MADERA, TERESITA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','MARTINEZ CAMPOS, GUSTAVO JOSE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','MIRANDA, PEDRO RUBEN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','ROBERTI, ALBERTO OSCAR',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','ROMERO, OSCAR ALBERTO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','RUBIN, CARLOS GUSTAVO',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','SNOPEK, GUILLERMO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','TENTOR, HECTOR OLINDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','TOMASSI, NESTOR NICOLAS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('JUSTICIALISTA','ZILIOTTO, SERGIO RAUL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('LIBERTAD, VALORES Y CAMBIO','ZIEGLER, ALEX ROBERTO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('LIBRES DEL SUR','COUSINET, GRACIELA',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('LIBRES DEL SUR','DONDA PEREZ, VICTORIA ANALIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('LIBRES DEL SUR','MASSO, FEDERICO AUGUSTO',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('MOVIMIENTO POPULAR NEUQUINO','SAN MARTIN, ADRIAN',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('MOVIMIENTO POPULAR NEUQUINO','VILLAR MOLINA, MARIA INES',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('MOVIMIENTO SOLIDARIO POPULAR','MARTINEZ, OSCAR ANSELMO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PARTIDO BLOQUISTA DE SAN JUAN','CASELLES, GRACIELA MARIA',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PARTIDO DEMOCRATA PROGRESISTA','COPES, ANA ISABEL',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PARTIDO SOCIALISTA','BINNER, HERMES JUAN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PARTIDO SOCIALISTA','CICILIANI, ALICIA MABEL',3,2,1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PARTIDO SOCIALISTA','DURE, LUCILA BEATRIZ',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PARTIDO SOCIALISTA','TROIANO, GABRIELA ALEJANDRA',5,'','',1);
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PRIMERO TUCUMAN','ORELLANA, JOSE FERNANDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PROYECTO SUR','ARGUMEDO, ALCIRA SUSANA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('PTS - FRENTE DE IZQUIERDA','BREGMAN, MYRIAM TERESA',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('SALTA SOMOS TODOS','OLMEDO, ALFREDO HORACIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('SOLIDARIO SI','HELLER, CARLOS SALOMON',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('TRABAJO Y DIGNIDAD','BERMEJO, SIXTO OSVALDO',4,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('TRABAJO Y DIGNIDAD','LAGORIA, ELIA NELLY',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNIDOS POR UNA NUEVA ARGENTINA','BREZZO, MARIA EUGENIA',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNIDOS POR UNA NUEVA ARGENTINA','BRÜGGE, JUAN FERNANDO',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNIDOS POR UNA NUEVA ARGENTINA','CALLERI, AGUSTIN SANTIAGO',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNIDOS POR UNA NUEVA ARGENTINA','NAZARIO, ADRIANA MONICA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNIDOS POR UNA NUEVA ARGENTINA','ROSSI, BLANCA ARACELI',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNIDOS POR UNA NUEVA ARGENTINA','RUCCI, CLAUDIA MONICA',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','ALBORNOZ, GABRIELA ROMINA',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','ALFONSIN, RICARDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','AUSTIN, BRENDA LIS',1,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','BANFI, KARINA VERONICA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','BARLETTA, MARIO DOMINGO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','BAZZE, MIGUEL ANGEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','BORSANI, LUIS GUSTAVO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','BURGOS, MARIA GABRIELA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','CARRIZO, ANA CARLA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','CARRIZO, MARIA SOLEDAD',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','COSTA, EDUARDO RAUL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','D''AGOSTINO, JORGE MARCELO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','DINDART, JULIAN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','ECHEGARAY, ALEJANDRO CARLOS AUGUSTO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','GIMENEZ, PATRICIA VIVIANA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','GOICOECHEA, HORACIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','GUTIERREZ, HECTOR MARIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','HERNANDEZ, MARTIN OSVALDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','KRONEBERGER, DANIEL RICARDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','MARCUCCI, HUGO MARIA',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','MARTINEZ, SILVIA ALEJANDRA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','MESTRE, DIEGO MATIAS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','MONFORT, MARCELO ALEJANDRO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','NANNI, MIGUEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','NEGRI, MARIO RAUL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','OLIVARES, HECTOR ENRIQUE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','PASTORI, LUIS MARIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','PETRI, LUIS ALFONSO',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','RICCARDO, JOSE LUIS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','RISTA, OLGA MARIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','ROQUEL, HECTOR ALBERTO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','SEMHAN, MARIA DE LAS MERCEDES',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','TOLEDO, SUSANA MARIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','TORROBA, FRANCISCO JAVIER',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','VALDES, GUSTAVO ADOLFO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION CIVICA RADICAL','VEGA, MARIA CLARA DEL VALLE',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION POR ENTRE RIOS','CREMER DE BUSTI, MARIA CRISTINA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','ACERENZA, SAMANTA MARIA CELESTE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','AMADEO, EDUARDO PABLO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','BALBO, ELVA SUSANA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','BALDASSI, HECTOR WALTER',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','BESADA, ALICIA IRMA',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','BUIL, SERGIO OMAR',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','CACERES, EDUARDO AUGUSTO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','CONESA, EDUARDO RAUL',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','DURAND CORNEJO, GUILLERMO MARIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','GARRETON, FACUNDO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','GAYOL, YANINA CELESTE',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','GONZALEZ, ALVARO GUSTAVO',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','GONZALEZ, GLADYS ESTHER',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','HERS CABRAL, ANABELLA RUTH',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','HUCZAK, STELLA MARIS',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','INCICCO, LUCAS CIRIACO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','LASPINA, LUCIANO ANDRES',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','LIPOVETZKY, DANIEL ANDRES',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','LOPARDO, MARIA PAULA',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','LOPEZ KOENIG, LEANDRO GASTON',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','LOSPENNATO, SILVIA GABRIELA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','MAQUIEYRA, MARTIN',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','MARTINEZ, ANA LAURA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','MARTINEZ, SOLEDAD',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','MASSOT, NICOLAS MARIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','MOLINA, KARINA ALEJANDRA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','MONZO, EMILIO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','NUÑEZ, JOSE CARLOS',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','PATIÑO, JOSE LUIS',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','PRETTO, PEDRO JAVIER',5,1,'','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','ROMA, CARLOS GASTON',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','SCAGLIA, GISELA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','SCHMIDT LIERMANN, CORNELIA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','SORGENTE, MARCELO ADOLFO',5,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','SPINOZZI, RICARDO ADRIAN',5,'',1,'');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','TONELLI, PABLO GABRIEL',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','TORELLO, PABLO',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','URROZ, PAULA',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','VILLALONGA, JUAN CARLOS',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','WECHSLER, MARCELO GERMAN',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','WISKY, SERGIO JAVIER',6,'','','');
INSERT INTO `website_asistencias` (bloque,nombre,presente,ausente,licencia,mo) VALUES ('UNION PRO','WOLFF, WALDO EZEQUIEL',6,'','','');
